In [1]:
import numpy as np

In [2]:
project_ids = np.load('../../data/processed/project_ids.npy')

In [3]:
len(project_ids)

1783

#### Find project_ids that were missed as part of the polling

In [4]:
'''
- In the first poll: id 280-312 (inclusive) failed to poll
- In the second poll: nothing failed to poll
- In the third poll: id=18862 failed to poll, 18999 failed to poll, 19535 failed to poll, 19847 failed to poll, 
'''
print(np.where(project_ids == 280))
print(np.where(project_ids == 312))
missed_in_first_poll = project_ids[139:167]

(array([139]),)
(array([166]),)


In [5]:
missed_in_first_poll

array([280, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296,
       297, 298, 299, 300, 301, 302, 303, 304, 305, 307, 308, 309, 310,
       311, 312])

In [6]:
print(np.where(project_ids == 18862))
print(np.where(project_ids == 18999))
print(np.where(project_ids == 19535))
print(np.where(project_ids == 19847))

(array([1450]),)
(array([1473]),)
(array([1555]),)
(array([1637]),)


In [7]:
missed_in_third_poll = project_ids[[1450, 1473, 1555, 1637]]

In [8]:
missed_in_third_poll

array([18862, 18999, 19535, 19847])

In [9]:
missed_project_ids = np.append(missed_in_first_poll, missed_in_third_poll)

In [10]:
missed_project_ids

array([  280,   285,   286,   287,   288,   289,   290,   291,   292,
         293,   294,   295,   296,   297,   298,   299,   300,   301,
         302,   303,   304,   305,   307,   308,   309,   310,   311,
         312, 18862, 18999, 19535, 19847])

In [11]:
np.save('../../data/processed/missed_project_ids', missed_project_ids)

In [12]:
len(missed_project_ids)

32