In [13]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_pickle('../../data/processed/active_profile_projects')

In [5]:
data_items = data.drop(columns=['profile'])

In [10]:
values = data_items.values.T

In [11]:
values.shape

(1781, 896)

In [18]:
values

array([[0, 1, 1, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [21]:
nonzeros = []
for i in range(0, values.shape[0]):
    nonzeros = nonzeros + [len(np.nonzero(values[i])[0])]

In [24]:
nonzeros = np.array(nonzeros)

In [26]:
np.argsort(nonzeros)[-1:]

array([0])

In [27]:
np.argsort(nonzeros)[-5:]

array([ 7, 11,  3,  1,  0])

In [28]:
np.argsort(nonzeros)[-10:]

array([12,  9, 14, 16, 13,  7, 11,  3,  1,  0])