In [50]:
import numpy as np
import pandas as pd

In [51]:
results = pd.read_json('../../experiments/cf-sci-results-128_5_2019-07-17-20-40-27.txt')

In [52]:
np.mean(results['precision'])

0.009597378277153557

In [53]:
np.mean(results['recall'])

0.0004794896057953456

In [54]:
results.iloc[results['precision'].idxmax()]

precision    1.000000
recall       0.004237
Name: 23, dtype: float64

In [55]:
predictions = np.load('../../experiments/autoencoder_cf_sci_y_pred_128_5.npy')

In [56]:
predictions.shape

(4866, 356)

In [62]:
recommended_project = np.nonzero(predictions[results['precision'].idxmax()])
recommended_project

(array([143, 146]),)

In [58]:
# Load the proejct data
users_projects = pd.read_pickle('../../data/processed/active_profile_projects')
projects = pd.read_pickle('../../data/processed/project_data')

In [59]:
projects_done_by_user_idx = np.nonzero(users_projects.iloc[269])

/Users/thomascartwright/miniconda3/envs/cdea/lib/python3.6/site-packages/numpy/core/fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


In [60]:
projects_done_by_user_idx

(array([  0,  22,  24, 265, 405, 546, 816]),)

In [63]:
recommended_projects_to_user_idx = (1781 - 356) + np.array(recommended_project)

In [67]:
recommended_projects_to_user_idx[0]

array([1568, 1571])

#### Get project titles

In [69]:
projects.iloc[projects_done_by_user_idx]['title']

0                                                 Foldit
22                Santa Fe National Forest Site Stewards
24     Stellar Classification Online Public Explorati...
265                     National Tree Benefit Calculator
405    New England Basking Shark and Ocean Sunfish Pr...
546                               Send us your skeletons
816           Stream Flow Monitoring in Upstate New York
Name: title, dtype: object

In [70]:
projects.iloc[recommended_projects_to_user_idx[0]]['title']

1570    Coastal Raptor Nest Behaviour Monitoring
1573         Barnstable Pond and Lake Monitoring
Name: title, dtype: object